In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("nyiso_dataset", engine="pyarrow")

In [3]:
#need to double check zone coords
zone_coords = {
    "CAPITL": (42.65, -73.75),
    "CENTRL": (43.05, -76.15),
    "DUNWOD": (41.01, -73.78),
    "GENESE": (43.17, -77.61),
    "HUD VL": (41.70, -73.93),
    "MHK VL": (42.10, -75.91),
    "MILLWD": (41.13, -73.78),
    "N.Y.C.": (40.71, -74.01),
    "NORTH": (44.70, -73.45),
    "WEST": (42.89, -78.87)
}

In [4]:
df

                  Time Stamp Time Zone    Name     PTID       Load  year month
0        2001-05-28 00:00:00       EDT  CAPITL  61757.0   894.0000  2001     5
1        2001-05-28 00:00:00       EDT  CENTRL  61754.0  1346.0000  2001     5
2        2001-05-28 00:00:00       EDT  DUNWOD  61760.0   415.0000  2001     5
3        2001-05-28 00:00:00       EDT  GENESE  61753.0   746.0000  2001     5
4        2001-05-28 00:00:00       EDT  HUD VL  61758.0   978.0000  2001     5
...                      ...       ...     ...      ...        ...   ...   ...
29327978 2025-10-03 23:55:00       EDT  MHK VL  61756.0   671.4786  2025    10
29327979 2025-10-03 23:55:00       EDT  MILLWD  61759.0   206.7461  2025    10
29327980 2025-10-03 23:55:00       EDT  N.Y.C.  61761.0  4669.4595  2025    10
29327981 2025-10-03 23:55:00       EDT   NORTH  61755.0   567.2412  2025    10
29327982 2025-10-03 23:55:00       EDT    WEST  61752.0  1410.2427  2025    10

[29327983 rows x 7 columns]

In [ ]:
import numpy as np
regions = df["Name"].unique()
timestamps = df["Time Stamp"].unique()
df_total_load = pd.DataFrame()
df_total_load["Time"] = timestamps
df_total_load["Load"] = np.zeros(len(timestamps))

for time in timestamps:
    df_total_load.loc[df_total_load["Time"] == time, "Load"] = df.loc[df["Time Stamp"] == time, "Load"].sum()

In [ ]:
training = df_total_load[:len(df_total_load)*0.8]
testing = df_total_load[len(df_total_load)*0.8:]
X_train, y_train = training["Time"], training["Load"]
X_test, y_test = testing["Time"], testing["Load"]

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

from sklearn.svm import SVR
svr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)
svr_rbf.train(X_train, y_train)
y_labels = svr_rbf.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_labels)

In [ ]:
# from datetime import datetime
# import matplotlib.pyplot as plt
# import meteostat
# from meteostat import Point, Daily, Hourly

# start = datetime(2018, 1, 1, 0, 0)
# end = datetime(2018, 1, 1, 12, 0)

# # Create Point for Vancouver, BC
# vancouver = Point(42.65, -73.75)

# # Get daily data for 2018
# data = Hourly(vancouver, start, end)
# data = data.fetch()

# # Plot line chart including average, minimum and maximum temperature
# data

,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco
time,,,,,,,,,,,
2018-01-01 02:00:00,-17.0,-22.9,60.0,<NA>,<NA>,290.0,20.5,<NA>,<NA>,<NA>,<NA>